### ISSUE TITLE
SafeString conflict with formatMessage

### ISSUE THREAD

**Issue by ronco** [jasonmit/ember-i18n-cp-validations#1]
Hi,

I was just testing this out with https://github.com/offirgolan/ember-cp-validations/pull/46 and ran into an issue.  The message being passed into [formatMessage](https://github.com/jasonmit/ember-i18n-cp-validations/blob/master/app/initializers/override-get-message-for.js#L32) is actually a SafeString from ember-i18n.  As a result the custom i18n message is getting replaced with the default invalid message because the type comparison fails [here](https://github.com/offirgolan/ember-cp-validations/blob/master/addon/validators/messages.js#L53).  Net result being an error message like this:
![](https://i.imgur.com/2fvgB0O.png)

**Comment by jasonmit** [comment]
That seems odd that ember i18n always assumes safestring.  Hopefully they are escaping all attributes then or that's a gnarly security issue.

Will look at this when I bring over the recent changes made to cp validations.

**Comment by jasonmit** [comment]
Addressed in 4b47b24224b316859c2d0fba59ee16bed0fa76a0

**Comment by ronco** [comment]
:+1:
