### ISSUE TITLE
Translating 'description' key of validator

### ISSUE THREAD

**Issue by caalle** [jasonmit/ember-i18n-cp-validations#10]
Hey,

Is there any plan on allowing translations of the description key? Something like this:

```
username: validator('presence', {
    presence: true,
    description: 'key.to.translation.username'
})
```

and in the `getDescriptionFor` do:

```
getDescriptionFor(attribute, options = {}) {
  const i18n = this.get('i18n');
  let key = `${this.get('prefix')}.description`;

  if (!Ember.isEmpty(options.description)) {
      key = options.description;
  }

  if (i18n && i18n.exists(key)) {
    return unwrap(i18n.t(key, options));
  }

  return this._super(...arguments);
}
```

Let me know what you think or if there's any other recommended way of translating the description.

**Comment by jasonmit** [comment]
@caalle great suggestion.  My only feedback, it might be nice if the description was left for string literals and translation description keys hang off a different property.  I'm opened to reviewing a PR for this, or can take this up in the future. :+1:
