### ISSUE TITLE
Support runtime recomputing error messages

### ISSUE THREAD

**Issue by jasonmit** [jasonmit/ember-i18n-cp-validations#12]

**Comment by jelhan** [comment]
Could add `i18n.locale` to `dependentKeys` as a work-a-round. Make sure `i18n.locale` gets consumed.

```
const Validations = buildValidations({
  title: [
    validator('length', {
      dependentKeys: ['i18n.locale'],
      min: 2
    })
  ]
});

export default Ember.Controller.extend(Validations, {
  init() {
    this.get('i18n.locale');
  },
  i18n: Ember.inject.service()
});
```

**Comment by jasonmit** [comment]
Yup, was opened prior to this being supported.  Closing now but thanks for adding details since others may not known!

**Comment by jelhan** [comment]
@jasonmit native support would be fine anyway. My work-a-round is far from being optimal: Property is revalidated if locale changes and a lot of boilerplate code is needed. I think we should leave this one open as a feature request.

**Comment by jelhan** [comment]
If you override `getDependentsFor` method of validators and add `_model.i18n.locale` you don't have to add `i18n.locale` over and over again to `dependentKeys`:

```
import Base from 'ember-cp-validations/validators/base';

Base.reopenClass({
  getDependentsFor() {
    return ['_model.i18n.locale'];
  }
});
```

You still have to inject i18n service to model and consume `i18n.locale`.

**Comment by jasonmit** [comment]
Unsure I want to go down that road, that's making the assumption that everyone injects the service with the i18n key.  While it's likely true for most, to me it doesn't feel right.  I'm opened to exploring ways to make this integration easier though, just unsure what that would look like.

Reopening for discussion

**Comment by jelhan** [comment]
It's not more than this changes to ember-cp-validations needed: https://github.com/jelhan/ember-cp-validations/commit/eeac8b575c38e69472fe04f785acf102b769aab7 Of course a refactoring would be necessary to let us override these internals.

**Comment by jasonmit** [comment]
Some coordination with @offirgolan would be necessary to expose that encapsulated type the factory method returns.

**Comment by jasonmit** [comment]
Required

**Comment by offirgolan** [comment]
> If you override getDependentsFor method of validators and add _model.i18n.locale you don't have to add i18n.locale over and over again to dependentKeys

This solution will not work since any validator that has dependents will override the base `getDependentsFor` method.

What I could do is always concat the contents of the dependents in `base` with every single validator's returned dependents which will allow you to add the `i18n` service dependent. 

> You still have to inject i18n service to model and consume i18n.locale.

In terms of service injection, I think the best solution would be to add documentation to tell users they have to inject the service in their model/component/etc. I dont really like the idea of forcefully injecting services.

**Comment by jasonmit** [comment]
I share this same opinion that this is best solved with documentation

**Comment by offirgolan** [comment]
Let me know if you want me to work on my first point or if you just prefer to add more documentation telling users to add the necessary dependentKeys to their global options.

**Comment by jasonmit** [comment]
https://github.com/offirgolan/ember-cp-validations/pull/146 resolved this with the ability to add "global" dependentKeys preventing having to add i18n.locale to each validation.
