### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by snewcomer** [jasonmit/ember-i18n-cp-validations#13]
I usually test my validation errors in integration tests.  Any thoughts on allowing this or am I missing test setup?  I can push up a fork with an integration test and all the setup if you would like.

**Comment by jasonmit** [comment]
@snewcomer this is a common issue with anything involving initializers, as initializers are not invoked during integration/unit tests.

You'll need to manually invoke the initializer for tests that are dependent on the functionality.  Something like the following should work:

``` js
import { moduleForComponent, test } from 'ember-qunit';
import initialize from 'ember-i18n-cp-validations/initialize';

moduleForComponent('x-product', 'XProductComponent', {
  integration: true,
  setup() {
    initialize(this);
  }
});
```

**Comment by snewcomer** [comment]
Sry didn't elaborate. Terrible issue description!  The problem I have is displaying the errors with the right translated value.  If I take `{{description}}` from the configuration, it displays `{This field} can't be blank` in the integration test result (with the setup) .  Moving it to an acceptance test gives the right translated value based on the specified description key.

I can push up an example with a test if you would like.

**Comment by jasonmit** [comment]
@snewcomer sounds good push to git and I'll take a look.

**Comment by snewcomer** [comment]
yep this one is my fault!  Sry about that.  Was only initializing ember-cp-validations. :(
