### ISSUE TITLE
[Feature Request] Supply default translations for common languages

### ISSUE THREAD

**Issue by simonihmig** [jasonmit/ember-i18n-cp-validations#14]
Hi there,

what's your thought on adding default translations to this addon, so that app authors writing apps in other languages than English would not have to provide their translations again and again?

One could just drop a translation file into this addon in `addon/locales/<lang>/translations.js`, which the app author would have to import and integrate into his app's translation file. 

As soon as https://github.com/jamesarosen/ember-i18n/issues/255 lands, one could just reexport that file into `app/locales/<lang>/ember-i18n-cp-validations.js`, so the manual integration step would be obsolete.

I could provide the German translations in a PR if you are willing to go that route, in fact I have them already lying around...

**Comment by jasonmit** [comment]
Sorry, I missed this being opened.  My only reservation is bundling translations inside of addon/\* ends up getting bundled into app.js.  Since we don't have tree shaking yet, this means they'll be pulling in translations that won't be used in the context of the user being served the assets.

But overall, I like the idea I'm just unsure about how to implement it right now.  Do you have any ideas?  Perhaps as a blueprint so users can do `ember g i18n-cp-validation de` for example and that will generate the translation module in `app/locales/en/ember-i18n-cp-validations.js`.  Thoughts?

**Comment by simonihmig** [comment]
Is it really like you said, that the translations would be part of app.js, even if they are only part of the `addon` tree and not the `app` tree, and they are not imported from the app itself? Have not tested that, but I assumed that the consuming app would only pull in the addon's `app` tree and everything that is imported from there!? So if you are not actively importing the translations, it would be left out. But actually I might be wrong... ?

**Comment by jasonmit** [comment]
> Is it really like you said, that the translations would be part of app.js, even if they are only part of the addon tree and not the app tree, and they are not imported from the app itself?

Correct, they get bundled into app.js.  When tree shaking lands, this will likely not be the default behavior anymore.  But it's unclear when that will land in ember-cli.

**Comment by offirgolan** [comment]
@jasonmit what if instead of bundling it, we create blueprints? That way others can contribute by adding blueprints to default error messages in their native tongue.

Something like 

```
ember g i18n-cp-errors --locale=fr
```

**Comment by jasonmit** [comment]
That's what I suggested above

**Comment by offirgolan** [comment]
LOL mb! I guess I missed it when I skimmed this over. 😵

**Comment by jasonmit** [comment]
:)

**Comment by offirgolan** [comment]
Glad we are on the same page 😝

**Comment by simonihmig** [comment]
@jasonmit you are right, it seems everything in the addon tree gets bundled (into vendor.js actually), regardless of whether it is imported from a module in the app tree or not. Just had a quick test. 

One could probably tackle this by using a Funnel on the treeForAddon hook, so the user can specify in his `ember-cli-build.js` which locales to include (or exclude). But that would require some additional work on the addon's side...

**Comment by simonihmig** [comment]
I feel maybe we should move this discussion to https://github.com/jamesarosen/ember-i18n/issues/255, to develop a best practice approach that all addons can follow, not an isolated solution just for this one...

**Comment by jasonmit** [comment]
Yeah, likely what should happen @simonihmig 

I've implemented addons being able to provide translations upstream tot he parent app in ember-intl, but a fair bit of work is needed to bring this over into ember-i18n.  In case someone wants to see how it works and perhaps submit a PR to bring it in.

Closing for now, feel free to reopen if ember-i18n bakes in support and we'll adopt it.
