### ISSUE TITLE
Missing translation: This field is invalid

### ISSUE THREAD

**Issue by nbehboudi** [jasonmit/ember-i18n-cp-validations#15]
I have installed this library but still I get the "Missing Translation' at the beginning of the validation error message. 

Missing translation: This field is invalid

**Comment by jasonmit** [comment]
can you push an example reproducing the issue?

**Comment by nbehboudi** [comment]
I put my validation in model:
import DS from 'ember-data'
import { validator, buildValidations } from 'ember-cp-validations';
  caption: {
    descriptionKey: 'key.for.caption',
    validators: [
      validator('format', {  
       regex: /^(?!\s*$)[-a-zA-Z0-9_:,.' ']{1,50}$/,
      }),
    ]  
  },

and in Locale I put the errors (as instructed in ember-i18n-cp-validations) as well as the key. The key gets replaced properly but I get missing Translation in front of the error message. am I missing anything? do I need to import "ember-i18n-cp-validations"? but I didnt see anything imported except ember-cp-validation in the example. 
   key: {
        for: {
            caption: 'Caption'
        }
    },

**Comment by jasonmit** [comment]
Nothing needs to be imported, can you add a failing test so it validates the bug is in the lib and not on your end.  Will speed up my ability to reproduce and fix it.

**Comment by jasonmit** [comment]
The code you posted is not correct, `descriptionKey` belongs inside of the validator.

``` js
  caption: {
    validators: [
      validator('format', {
        descriptionKey: 'key.for.caption',
        regex: /^(?!\s*$)[-a-zA-Z0-9_:,.' ']{1,50}$/,
      }),
    ]
  }
```

**Comment by nbehboudi** [comment]
Still getting the same result (already made the change you mentioned) : 
Missing translation: Caption is invalid

**Comment by jasonmit** [comment]
I can only help you further if you can reproduce the issue in isolation and push an example to github
