### ISSUE TITLE
messageKey does not work

### ISSUE THREAD

**Issue by Reinmar-De-Grasse** [jasonmit/ember-i18n-cp-validations#18]
I have:
app/locales/en/translations.js

``` javascript
export default {
  custom_errors: {
    empty_entity_name: "Enter entity name"
  }
};
```

app/models/entity.js

``` javascript
const Validations = buildValidations({
  name: validator('presence', {presence: true, messageKey: 'custom_errors.empty_entity_name'})
});
export default DS.Model.extend(Validations, {
  name: DS.attr('string')
});
```

but my messageKey just ignored at getMessageFor: i18n.t(key, options) and errors.blank used

``` javascript
/*
key "errors.blank"
options {description:"This field"
messageKey:"custom_errors.empty_entity_name"
presence:true}
*/
return this.formatMessage(unwrap(i18n.t(key, options))); //"This field can't be blank"
```

**Comment by jasonmit** [comment]
Did you specify the prefix as `custom_errors` as documented here: https://github.com/jasonmit/ember-i18n-cp-validations#customizing-the-prefix

Maybe in the future I'll drop the `prefix`, but currently that's required if you are namespacing under `custom_errors` instead of the default `errors`

**Comment by Reinmar-De-Grasse** [comment]
With prefix (app/validators/messages.js):

``` javascript
import ValidatorsMessages from 'ember-cp-validations/validators/messages';

export default ValidatorsMessages.extend({
  prefix: 'custom_errors'
});
```

and:

``` javascript
  name: validator('presence', {presence: true, messageKey: 'custom_errors.empty_entity_name'}),
```

i got:
{description} can't be blank

With prefix and:

``` javascript
  name: validator('presence', {presence: true, messageKey: 'empty_entity_name'}),
```

i got:
{description} can't be blank

I just want custom path to error message for concrete field.
May be custom path inside default "errors". How?

**Comment by jasonmit** [comment]
https://github.com/jasonmit/___i18ncpvalidationsmessagekey/commit/d33d26b102b0d5437ca3c77fd80f9b05072f9ce9

I cannot reproduce this, run the above app and look at what I am doing versus what you have in your project.  Reopen if you still have issues and can reproduce it with an example app like the one above.

**Comment by Reinmar-De-Grasse** [comment]
I think it was an older version of ember-i18n-cp-validations (2.6.0 in your link versus my 2.4.0).

I update all dependencies up to your example and it works now. Thank you!
