### ISSUE TITLE
Update for ember-cp-validations ^ 3.0.0 ?

### ISSUE THREAD

**Issue by Kilowhisky** [jasonmit/ember-i18n-cp-validations#19]
It appears that this addon doesn't work with the latest beta of ember-cp-validations. Can we get a beta that works with it?

**Comment by Kilowhisky** [comment]
Actually it was because i didn't realize that you had to specify the full key path when using `messageKey`.  so `badPhone` actually had to be `errors.badPhone`.

**Comment by jasonmit** [comment]
Let me know if the docs could be improved to avoid this in the future.
