### ISSUE TITLE
Add conditionals in error messages

### ISSUE THREAD

**Issue by IAmJulianAcosta** [jasonmit/ember-i18n-cp-validations#20]
Hi! I'm trying use genders in my translation, like this:

```
invalid                : "{{description}} es {{#if gender}}inválido{{else}}inválida{{/if}}",
```

But it seems that is not working. Is this supported?

**Comment by jasonmit** [comment]
Not that I'm aware of. It is whatever ember-i18n supports since it defers to i18ns compiler. 

It might be useful to open up a discussion on ember-i18n around how others implement gender within translations.

The best I can recommend is to pass the dynamic portions as an attribute.

**Comment by IAmJulianAcosta** [comment]
@jasonmit could you please help me with an example of dynamic portions? I'm just starting with ember-i18n and don't know how to do it.

Thanks!

**Comment by jasonmit** [comment]
Certainly.  I only have access to my phone until Monday so I'll put together an example then.  Thanks

**Comment by IAmJulianAcosta** [comment]
Hi Jason, just a friendly reminder :)

Julián Acosta

**Comment by jasonmit** [comment]
``` js
age: validator('presence', {
  presence: true,
  // this will be invoked everytime the age attr changes
  gender(/* model */) {
    // logic for determining gender here
    return 'dynamic, will be inserted in the gender placeholder';
  }
})
```

``` yml
blank: "{{description}} es {{gender}}"
```

If you want, I'd love if you could update the README in a way that would make sense for others.  I haven't had a use for this, but clearly the docs are lacking to make this known.

**Comment by jasonmit** [comment]
Updated README to reflect this and wrote a test to cover support for passing attributes which should address the underlying concern.  The tests in #21 may be more useful than the contrive example I gave above.

Feel free to reopen if you have any other questions.
