### ISSUE TITLE
Unclear how to translate {{on}} in confirmation

### ISSUE THREAD

**Issue by toovy** [jasonmit/ember-i18n-cp-validations#27]
Hi, 

I cannot find any information about translating the {{on}} part in a confirmation:

    confirmation: "{{description}} doesn't match {{on}}",

My validator looks like this:

    validator('confirmation', on: 'newPassword')

Any hint?

Thanks, BR, toovy

**Comment by jasonmit** [comment]
```
validator('confirmation', on: 'newPassword')
```

Isn't valid JavaScript, did you mean: `validator('confirmation', { on: 'newPassword' })`?

If so, I believe the output would be "This field doesn't match on newPassword".  If that's not happening, I'll whip up a fail test and patch if it is indeed a bug.

**Comment by toovy** [comment]
I'm so sorry, it is valid coffee-script :). The output is correct. the part "newPassword" in "This field doesn't match on newPassword" needs a human readable (and translated) string.

**Comment by jasonmit** [comment]
Okay, now I understand.

I am unsure how `on` is used within the validator itself so I'll go on the assumption that this is a key to a property and not a string literal.  If that's true, I would not want to reuse that field unless you want it in the literal string sense `"newPassword"`.

If you want to dynamically compute it or have more control, change `{{on}}` to `{{fieldName}}` (fieldName is arbitrary, it can be named anything) and then define a method on the validator with that same key.  This will get invoked each it is validated and the return value of the method will be used.

Example:

``` js
validator('confirmation', {
  on: 'newPassword',

  // will be invoked each time a validation occurs
  fieldName(/* instanceOfThingBeingValidated */ ) {
    return 'new password!';
  }
})
```

and then your translation needs to change to:

``` yml
confirmation: "{{description}} doesn't match {{fieldName}}"
```

Let me know if this doesn't work, or if you have issues with it.

Here is an example of a custom `range` validator which does what I just described.
[tests/dummy/app/models/dummy.js#L23-L45](https://github.com/jasonmit/ember-i18n-cp-validations/blob/master/tests/dummy/app/models/dummy.js#L23-L45)

**Comment by toovy** [comment]
You are right, the on property is a reference to the other property, but due to this fact also the literal that is displayed.

That solved my problem, just for reference, I needed to use a computed property instead of a function.

translation.js

```
confirmation: "{{description}} stimmt nicht mit '{{otherFieldName}}' überein"
```

model

```
validator('confirmation', on: 'newPassword', otherFieldName: Ember.computed '', -> 'Neues Passwort')
```

Your support is very much appreciated. Thanks a lot!

**Comment by fsmanuel** [comment]
Thanks for the solution!
