### ISSUE TITLE
Warning message when running Tests: "Missing translation for validation key" 

### ISSUE THREAD

**Issue by frunjik** [jasonmit/ember-i18n-cp-validations#28]
I have a model field with a custom validator (named urlChars).
I have put a translation in the locales/*/translations.js file with key errors.urlChars.
The app behaves correctly.
When running my (acceptance) tests, I get this message (in browser and PhantomJS):

> initialize.js:43[ember-i18n-cp-validations] Missing translation for validation key: errors.urlChars
> 

Is there something i need to do (in test mode) to make the message go away ?

Ember             : 2.4.5
Ember Data        : 2.5.0
jQuery            : 2.2.3
Ember Simple Auth : 1.0.0

"ember-i18n": "4.2.0",
"ember-cp-validations": "2.4.1",
"ember-i18n-cp-validations": "2.7.2",

**Comment by jasonmit** [comment]
I can add an environment variable and in `config/environment.js` you could do:

``` js
module.exports = function(environment) {
  var ENV = {};

  if (environment === 'test') {
    ENV.i18n = ENV.i18n || {};
    ENV.i18n.suppressMissingWarning = true;
  }

  return ENV;
}
```

`
Will that work for you?

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-i18n-cp-validations/commit/bc0c9113393183524040f1c57a0636583d26725d should fix, I'll version once tests pass

**Comment by jasonmit** [comment]
Part of 2.8.0

**Comment by frunjik** [comment]
Just confirming that this indeed gets rid of the warnings.
I'm assuming it also means that translating the messages in tests does not work ?

 :+1: for the quick fix

**Comment by jasonmit** [comment]
> I'm assuming it also means that translating the messages in tests does not work ?

@frunjik correct, assuming you only set `suppressMissingWarning` to true in the test environment.

**Comment by alexmiddeleer** [comment]
In case anyone googled their way here, it's just `ENV.i18n.suppressWarnings = true;` now I believe (in 3.0.2 anyway)

**Comment by jasonmit** [comment]
Correct.  https://github.com/jasonmit/ember-i18n-cp-validations#disabling-missing-translation-warnings
