### ISSUE TITLE
The variable "count" is unaveilable for interpolation. I am using "min", "max"...

### ISSUE THREAD

**Issue by phcoliveira** [jasonmit/ember-i18n-cp-validations#3]
Hi there!

Despite de docs, I can't find a way to make the messages for the validators which rely on {{count}} to work properly.

They work, however, with the variables passed as options when defining a validator, such {{min}} and {{max}}.

**Comment by jasonmit** [comment]
offirgolan/ember-cp-validations@0475902 introduced this but I've versioned a fix under ember-i18n-cp-validations@2.1.4

I plan to keep the versions in lock step going forward to prevent confusion if a breaking change is introduced upstream.
