### ISSUE TITLE
MessageKey computed property?

### ISSUE THREAD

**Issue by alexmiddeleer** [jasonmit/ember-i18n-cp-validations#36]
Hi there, I was wondering whether it was possible to have two possible translations for a given validation. For example, I have a field that needs an error message "please provide a message" if the message is blank and "message max length is X" if the message is too long. I tried making `messageKey` a computed property, but this debugger isn't getting hit:

```
    messageKey: computed('model.myField', function() {
      debugger;
    }),
```

**Comment by jasonmit** [comment]
@alexmiddeleer currently unsupported but happy to add it.

**Comment by alexmiddeleer** [comment]
Let me know if I can be of help.

**Comment by jasonmit** [comment]
Based on your example, you can handle this behavior with multiple validators.

Something like the following:

```js
buildValidations({
  myField: [
    validator('presence', true),
    validator('length', {
      messageKey: 'errors.invalidLength',
      min: 4,
      max: 8
    })
  ]
})
```

**Comment by alexmiddeleer** [comment]
Thanks!
