### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath 

### ISSUE THREAD

**Issue by villander** [jasonmit/ember-i18n-cp-validations#39]
The following deprecation is thrown on a new Ember 2.18.0/2.18.1 Version. It seems some package needs to be updated.

DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/michaelvillander/Projects/vzon-ui/node_modules/ember-i18n-cp-validations/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

We can update this addon for Ember 2.18 and generate new release? I can do a PR to solve this

**Comment by jasonmit** [comment]
@villander yes please to the PR offer :)

**Comment by jasonmit** [comment]
Issue should be resolved within 3.1.0, thanks
