### ISSUE TITLE
can't install ember install ember-i18n-cp-validations

### ISSUE THREAD

**Issue by bedrosenator** [jasonmit/ember-i18n-cp-validations#40]
After ember install ember-i18n-cp-validations I got
Command failed: yarn add --dev ember-i18n-cp-validations --non-interactive
Usage: yarn [options]

yarn: error: no such option: --dev

Stack Trace and Error Report: /tmp/error.dump.4c87055416522921ce9c4d9fcaaaea95.log

Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty

**Comment by jasonmit** [comment]
@bedrosenator likely an ember-cli issue, as I don't have a blueprint or any custom install logic. Feel free to reopen if you can reproduce with a fresh install of ember-cli.  Be sure to also include the version of ember-cli you were using.
