### ISSUE TITLE
Use reopenClass in initializer for service injection

### ISSUE THREAD

**Issue by blimmer** [jasonmit/ember-i18n-cp-validations#5]
Since the i18n service was being included in a `reopen` vs. a `reopenClass`, the service injection is shared by multiple tests with different containers, causing this exception.

``` bash
Assertion Failed: Attempting to lookup an injected property on an object without a container,
ensure that the object was instantiated via a container.
```

I will happily port this change to the intl flavor of this addon once this has a second set of eyes.

**Comment by blimmer** [comment]
Without this fix, two subsequent unit tests on validations on `DS.Model`s would throw this exception:

```bash
Assertion Failed: Attempting to lookup an injected property on an object without a container,
ensure that the object was instantiated via a container.
```

Causing tests to fail.

**Comment by blimmer** [comment]
Crap, maybe this doesn't work because now I'm getting errors. Would love a second set of eyes on this.

**Comment by jasonmit** [comment]
I'm not sure I fully understand the problem, can you create a little dummy app that throws this assertion failure.

It seems somewhere that the `validators/messages` instances are being created outside of the container which would result in the assertion failure you're seeing.  I'm reopening in the initializer, not creating instances or looking up instances so I believe it's safe.
