### ISSUE TITLE
{description} is not replaced unless defining all messages using {{description}}

### ISSUE THREAD

**Issue by bschouwerwou** [jasonmit/ember-i18n-cp-validations#9]
Hi,

I'm trying this out, but I've noticed that the defaults in ember-cp-validations use a single pair of curly brackets in its defaults (like `{description}`), but this one requires them to have two (like `{{description}}`).

In my case while testing things out, I've defined my own `errors.description` as `"test"`. Since I have not defined my own message for `errors.blank` I expected it to use the defaults and output "test can't be blank", however I'm getting "{description} can't be blank".

If I define a message for `errors.blank` that uses the `{{}}` it will work, or if I modify the `_regex` property in initialize.js to match (`/\{{(\w+)\}}/g` to `/\{(\w+)\}/g`) it works.

Am I missing something or is this some disconnect between the two packages in this regard?

**Comment by jasonmit** [comment]
It's to keep the syntax aligned with ember-i18n translations -- this is intended.  Feel free to submit a PR to update the README that would make this more obvious if you'd like. :+1:
